# https://circleci.com/docs/2.0/

version: 2
workflows:
  version: 2
  ci:
    jobs:
      - lint
      - build-image
      - deploy

      - build-macos:
          requires:
            - "build-image"

      - build-linux:
          requires:
            - "build-image"

jobs:
  lint:
    docker:
      # https://circleci.com/docs/2.0/circleci-images/
      # https://hub.docker.com/r/circleci/python/
      - image: "circleci/python:3"

    steps:
      - "checkout"

      - run:
          name: "setup Python environment"
          command: |
            echo "setup Python environment"

      - run:
          name: "run lint checks"
          command: |
            echo "run lint checks"

  build-image:
    docker:
      # https://circleci.com/docs/2.0/circleci-images/
      # https://hub.docker.com/r/circleci/python/
      - image: "circleci/python:3"

    steps:
      # https://circleci.com/docs/2.0/building-docker-images/
      - setup_remote_docker:
          docker_layer_caching: true

      - "checkout"

      - run:
          name: "build and push image"
          command: |
            docker login -p "$DOCKER_PASSWORD" -u d6eautomaton
            echo "env var for Docker password worked"

  deploy:
    machine:
      enabled: true
      # https://circleci.com/docs/2.0/configuration-reference/#machine
      image: "circleci/classic:201711-01"

    steps:
      - run:
          name: "update system"
          command: |
            sudo apt-get --quiet update

      - "checkout"

      - run:
          name: "deploy"
          command: |
            pyenv global 2.7.12 3.5.2
            python3 --version
            mkdir dist
            echo "deployed"

      - store-artifacts:
          path: dist

  build-linux:
    machine:
      enabled: true
      # https://circleci.com/docs/2.0/configuration-reference/#machine
      image: "circleci/classic:201711-01"

    environment:
      - PROJECT_NAME: "datawireio"

    steps:
      - run:
          name: "update system"
          command: |
            sudo apt-get --quiet update

      - "checkout"

      - run:
          name: "decrypt gcloud keys"
          command: |
            # To update:
            #   1) Generate a new key and IV:
            #      $ dd if=/dev/urandom count=64 bs=1 | md5sum
            #   2) Update GCLOUD_KEY and GCLOUD_IV in CircleCI "Environment
            #      Variables" configuration for Telepresence project.
            #   3) Encrypt the new gcloud key:
            #      $ ci/encrypt-gcloud-key circleci $GCLOUD_KEY $GCLOUD_IV
            true $GCLOUD_KEY $GCLOUD_IV
            echo "decrypt gcloud keys"

      - run:
          name: "setup non-Python environment"
          command: |
            # https://raw.githubusercontent.com/circleci/image-builder/picard-vm-image/provision.sh
            pyenv global 2.7.12 3.5.2
            echo "setup non-Python environment"

      - run:
          name: "setup Python environment"
          command: |
            echo "setup Python environment"

      - run:
          name: "run tests"
          command: |
            echo "run tests"

  build-macos:
    macos:
      xcode: "9.0"

    environment:
      - PROJECT_NAME: "datawireio"

    steps:
      - "checkout"

      - run:
          name: "decrypt gcloud keys"
          command: |
            # To update:
            #   1) Generate a new key and IV:
            #      $ dd if=/dev/urandom count=64 bs=1 | md5sum
            #   2) Update GCLOUD_KEY and GCLOUD_IV in CircleCI "Environment
            #      Variables" configuration for Telepresence project.
            #   3) Encrypt the new gcloud key:
            #      $ ci/encrypt-gcloud-key circleci $GCLOUD_KEY $GCLOUD_IV
            true $GCLOUD_KEY $GCLOUD_IV
            echo "decrypt gcloud keys"

      - restore_cache:
          key: "system-components"

      - run:
          name: "setup non-Python environment"
          command: |
            echo "setup non-Python environment"

      - save_cache:
          key: "system-components"
          paths:
            - "~/Library/Caches/Homebrew"
            - "~/google-cloud-sdk/"

      - restore_cache:
          key: |
            pip-http-cache-{{ .Branch }}-{{ checksum "dev-requirements.txt" }}-{{ checksum "k8s-proxy/requirements.txt" }}-{{ checksum "setup.py" }}

      - run:
          name: "configure gcloud"
          command: |
            echo 'PATH=${HOME}/google-cloud-sdk/bin:${PATH}' >> ${BASH_ENV}
            # If we installed kubectl, it was into ${PWD}
            echo 'PATH=${PWD}:${PATH}' >> ${BASH_ENV}

      - run:
          name: "setup Python environment"
          command: |
            echo "setup Python environment"

      - save_cache:
          key: |
            pip-http-cache-{{ .Branch }}-{{ checksum "dev-requirements.txt" }}-{{ checksum "k8s-proxy/requirements.txt" }}-{{ checksum "setup.py" }}
          paths:
            # OSX specific
            - "~/Library/Caches/pip/"

      - run:
          name: "run tests"
          command: |
            echo "run tests"
